// Code generated by hertz generator.

package main

import (
	handler "proxy_server/biz/handler"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	whipGrop := r.Group("/whip")
	{
		whipGrop.GET("/ping", handler.Ping)
		whipGrop.POST("/proxy", handler.Proxy)

		// only for test
		whipGrop.POST("/genToken", handler.GenTokenForTest)
	}
}
