// Code generated by hertz generator.

package handler

import (
	"context"
	"net/http"

	"github.com/cloudwego/hertz/pkg/app"
)

// Ping .
func Ping(ctx context.Context, c *app.RequestContext) {
	c.String(http.StatusOK, "pong")
}
