# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WebRtcDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Masonry'
  pod 'YYModel'
  pod 'AFNetworking', '~> 4.0'
  # Pods for WebRtcDemo

  target 'WebRtcDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WebRtcDemoUITests' do
    # Pods for testing
  end

end
